name = "Joysticks"
uuid = "82f05805-4863-42dc-b1a7-0852bd62c632"
authors = ["Uwe Fechner <fechner@aenarete.eu> and contributors"]
version = "0.1.1"

[deps]
Observables = "510215fc-4207-5dde-b226-833fc4488ee2"

[compat]
julia = "1"
Observables="0.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
